### ISSUE TITLE
[Bug] Query diff - Double rounding issue

### ISSUE THREAD

**Issue by julien-alpaca** [DataRecce/recce#519]
### Current Behavior

When comparing 2 same double values, recce show them as different because of the rounding.

<img width="1374" alt="image" src="https://github.com/user-attachments/assets/b5903500-82bf-44a9-b8ad-13ecfd0d0889">

I understand that this is the inherent behaviour of double that are floating points.

### Expected Behavior

Have a tolerance configuration for double diff.

```
epsilon = 1e-9
if abs(a - b) < epsilon:
    print("a and b are approximately equal")
```

### Steps To Reproduce

1. Query a query diff with a table that contains a double type column

### Environment

- recce: 0.42.0
- OS: Mac
- Python: 3.12
- Data Warehouse: Trino/iceberg
- dbt: 1.8.6

**Comment by clkao** [comment]
@julien-alpaca thanks for raising the issue!

I'd love to learn a bit more about the query diff in order to design a good experience for adding the tolerance:

1. are there any changes in your PR about how subtotal was computed? or all changes are impacting other column but you're seeing the difference from rounding
2. are you able to add rounding in the query you use for the query diff? if not, what would be the reason?

Since the backend is using audit-helper, the different rows are provided by the warehouse. One option is to filter results in frontend, but this might not be the best way.

**Comment by popcornylu** [comment]
> are you able to add rounding in the query you use for the query diff? if not, what would be the reason?

Here is an example query you can use to round the column.
```sql
SELECT
   __unique_key,
   volumn,
   ROUND(subtotal, 9) AS rounded_subtotal
FROM
   MyTable
```

Under the hood, we use audit-helper to diff, which performs an exact match to compare the values of two columns.

**Comment by julien-alpaca** [comment]
Thank you @clkao @popcornylu for your quick answer. We will change all double in decimal and that should fix the issue. Two same double values will display as a difference in recce but this is because double are floating points. Thank you for you help!

**Comment by alexeyegorov** [comment]
> Thank you [@clkao](https://github.com/clkao) [@popcornylu](https://github.com/popcornylu) for your quick answer. We will change all double in decimal and that should fix the issue. Two same double values will display as a difference in recce but this is because double are floating points. Thank you for you help!

How did you approach this? We tried rounding the values with a DBT macro (could share this with you), but on Databricks this means to reproduce the whole table again and rewrite the results... this is compute intensive. :/
